### PR TITLE
Cards UI break resolved #92

### LINKED ISSUE #92: Bug on Firefox browser
Due to a div's height, 2 of the card of home page on firefox browser is creating misalignment
screenshot-codingblocks com 2017-05-23 14-00-13
screenshot from 2017-05-23 14-15-48

### PR DESCRIPTION
**Pull request by astu9880**
Fixes #92 
@championswimmer @prateek27 Please review.

### CODE REVIEW

**Comment by astu9880** [comment]
@championswimmer @prateek27 
**Screenshots:**
screenshot from 2017-05-29 18-23-21

**Comment by astu9880** [comment]
@championswimmer Please take a look

**Comment by prateek27** [comment]
@Prajjwal @omerjerk  Can you review @astu9880 's code ?

**Comment by Prajjwal** [comment]
Please do the following:

- Correct formatting. Put a space before opening parens.
- Put styles in the `.pricing-table` class instead of `.pcard`. Having two similarly named classes doing the same thing is bad practice.

**Comment by astu9880** [comment]
@Prajjwal 
- formatting corrected
- used already made pricing card class instead of pricing table as it did not target the required divs.
- pricing-card used only in coming-soon.html other than the home page. Working fine there too.
Thanks for reviewing :)
Is there anything else?

**Comment by Prajjwal** [comment]
Good job! Tested on Firefox. Should be okay to merge. 👍

**Comment by astu9880** [comment]
@prateek27

**Pull request merged**
