### PR TITLE
#30 First three course logos changed to svg

### PR DESCRIPTION
**Pull request by adarsh1021**
For issue #30 

I have converted the first three course logos to svg format. (color_algo, color_android and color_chatbots)
Kindly review them and confirm this is how you want them. 
I will work on the rest of the logos and convert them into svg after your approval.

### CODE REVIEW

**Comment by championswimmer** [comment]
Screenshots please for UI changes :)

**Comment by adarsh1021** [comment]
These are the three course logos that I converted to svg format.
Please review them and confirm this is how you want them.
I will work on the rest after your approval

_test1
_test2
_test3

**Comment by Akshay-parashar** [comment]
Sir i would like to point out that the images he posted clearly dont look so sharp and no offence but they look like they were converted from some online tool. here is the logo that i made in illustrator so if you'd appreciate my effort i would convert all the course logo's to SVG.

screenshot 6

**Comment by adarsh1021** [comment]
The images are a screenshot obviously. I have used illustrator. Please review my pull request.

**Comment by prateek27** [comment]
@adarsh1021 please do not delete the original png files. we want to keep them, if required in future (or as fallback for places where svg wont work)

**Comment by prateek27** [comment]
@Akshay-parashar  nice work but one who does it first, will be counted.
@adarsh1021 SVG's are looking fine, here he has pasted screenshots that might be the reason.
@adarsh1021  Please submit other logos as well, and add original PNG's files. Will merge your PR.

**Pull request merged**
