### PR TITLE
Kids and Online Layout Changed

### PR DESCRIPTION
**Pull request by hereisnaman**
Layout changed as per request. Issue: https://github.com/coding-blocks/coding-blocks.github.io/issues/74

## ScreenShot
image

### CODE REVIEW

**Comment by prateek27** [comment]
@hereisnaman @bhavyaagg Pls submit images of your mobile layout. I want to compare.

**Comment by prateek27** [comment]
@hereisnaman  @bhavyaagg 
change the text - ONLINE COURSES
Launchpad online course on Data Structures & Algorithms starting from June 5. Enroll before 1st June and get 50% OFF on course fee.

**Comment by bhavyaagg** [comment]
@prateek27 bhaiya updated my pr with the mobile views.

**Comment by hereisnaman** [comment]
@prateek27, @bhavyaagg is having more responsive layout. Closing this PR.

**Pull request closed without merging**
