### PR TITLE
Slider Added

### PR DESCRIPTION
**Pull request by hereisnaman**
Slider added with pics from FB, saved locally. Kept only h2 in slider info, commented other code. 
Will optimize images in next PR. 

Against BOSS Issue: https://github.com/coding-blocks/coding-blocks.github.io/issues/72

Bounty: 100

### CODE REVIEW

**Comment by prateek27** [comment]
Height should be reduced by 25% , List view should be visible.

**Comment by prateek27** [comment]
Upcoming needs a spelling correction.

**Comment by hereisnaman** [comment]
Sorry, resolving in next pr.

**Comment by prateek27** [comment]
Also remove the Summer Courses for Kids Slide not reqd.

**Comment by prateek27** [comment]
If needed adjust the background position of some pics ( like in the first photo )

**Pull request merged**
