### PR TITLE
BOSS LOGOS

### PR DESCRIPTION
**Pull request by ArushiSinghal**
@championswimmer ISSUE #121

### CODE REVIEW

**Comment by championswimmer** [comment]
The logo files should be square-cropped to the logo only, not large rectangles with lots of white

**Comment by ArushiSinghal** [comment]
@championswimmer please review.

**Comment by ArushiSinghal** [comment]
@championswimmer Is there any changes required?

**Comment by championswimmer** [comment]
Didn't notice earlier, but these should go to boss repo, not this repo.

**Comment by ArushiSinghal** [comment]
@championswimmer  
https://github.com/coding-blocks/boss-backend Is this the correct Repo?

**Pull request closed without merging**
