### PR TITLE
Added Analytics Tracking Code

### PR DESCRIPTION
**Pull request by hereisnaman**
@Prajjwal @witty123

### CODE REVIEW

**Comment by witty123** [comment]
@hereisnaman We already have GA tracking. Why is this PR required ?

**Comment by hereisnaman** [comment]
Thats the GA tracking code, I can't see that in the live page source, neither I can see any real time views in the analytics nor anywhere else (from this project, not /resources).

GA code is present  neither in `head` nor in `scripts` partials, which are the only site-wide used partials.

**Comment by witty123** [comment]
If that's the case then events in resources and other modules will get tracked twice.

**Comment by hereisnaman** [comment]
They are separate repos, no sharing of source code. This project belongs to the website only. On other projects like resources, the tracking code is there but missing in this website project. 

We are receiving about 10K organic hits per month but no trace in analytics.

**Pull request merged**
